version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Database=CryptoExchangeDb;Username=postgres;Password=postgres
      DataFolderPath: /app/ExchangesData
    volumes:
      - ./ExchangesData:/app/ExchangesData

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CryptoExchangeDb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: